### ISSUE TITLE
과제 p 35질문

### ISSUE THREAD

**Issue by illulia** [gitksh/qna#3]
```c
#include <stdio.h>

int main()
{
	long outm, money, mpy;
	int count = 0;
	
	scanf("%ld %ld %ld", &money, &mpy, &outm);
	
	while(money>=0)
	{
		money = money + money*(mpy*0.01) - outm;
		count = count + 1;	
	}
	
	printf("%d", count);
	
	return 0;
}
```

```python
money, mpy, outm = map(int,input().split())
count = 0

while money>=0:
    money = money + money*(mpy*0.01) - outm
    count = count + 1

print("%d" %count)
```

//각각 35번 문제를 c언어랑 pthon으로 작성했는데 입력 예제 3,4번의 답이 다르게 나와요 (python이 맞게 나옴)
//뭐가 문제 일까요...

**Comment by gitksh** [comment]
C는 변수 선언시 변수형이 매우 중요합니다.

```c
money = money + money*(mpy*0.01) - outm;
```

이 줄을 보면 `money`에 `mpy*0.01` 이라는 실수를 곱하는 것을 보실 수 있습니다.

```c
long outm, money, mpy;
```
하지만 변수 선언을 long으로 했기 때문에 실수가 곱해져도 정수형으로만 변수 안에 값이 들어가게 됩니다.

즉, 변수형을 모두 double이나 float로 바꾸면 됩니다.

여담으로 파이썬의 map 함수는 절대로 변수형을 지정해주는 것이 아닙니다.

```python
money, mpy, outm = map(int, input().split())
```
이 줄에서 `map(int, input().split())` 으로 값을 입력받지만, `money, mpy, outm` 변수들은 절대 int형이 아니게 됩니다.

map은 단지 입력 받은 값을 정수형(int)로 바꿔서 변수에 값을 넣는 것입니다.

즉  `10.5 2.5 3.6`을 입력하더라도 정수인 `10 2 3`이 변수에 각각 들어가게 됩니다.
