### ISSUE TITLE
c언어 P022 질문

### ISSUE THREAD

**Issue by hongi1547** [gitksh/qna#5]
```c
#include <stdio.h>

int main()
{
	int n;
	
	scanf("%d", &n);
	
    printf("%c%d", (n+8)%12+'A', (n+6)%10);
    
    return 0;
}
```
이 코드에서 프린트 f 부분에 (N+8)에서 8을 더하는 이유가 뭔지 궁굼합니다..

**Comment by gitksh** [comment]
입출력의 예시에서 **2017**을 입력하면 **J** 가 출력됩니다. 

이때 J는 아스키코드 상 **74**번으로 65에서 **9**만큼 더해야지 나옵니다.

2017에 x만큼 더한뒤 12로 나눴을때 나머지로 9가 나오기 위해서는 2017에 8을 더해야 합니다.

(2017+8)%12 + 65 = 74 = J
